server:
  port: ${CUSTOM.SERVER.PORT:8765}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuario/**
          filters:
            - StripPrefix=2
        - id: licencia-service
          uri: lb://licencia-service
          predicates:
            - Path=/api/licencia/**, /api/cliente/**
          filters:
            - StripPrefix=2
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS

config:
  security:
    privateKey: 3a27f63a56e28002f3d35b85aaa716d596039fbc942515f38f1e25d7100eb412

management:
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true
