server:
  port: ${CUSTOM.SERVER.PORT:8005}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

spring:
  application:
    name: auditoria-service
  data.mongodb:
    uri: mongodb://root:password1234@localhost:27017/db_audit?authSource=admin
    database: db_audit
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: auditoriagroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    topic:
      name: usuario_topics

management:
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true
