server:
  port: ${CUSTOM.SERVER.PORT:8005}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

spring:
  application:
    name: auditoria-service
  data.mongodb:
    uri: mongodb://root:password1234@localhost:27017/db_audit?authSource=admin
    database: db_audit

kafka:
  topic:
    usuarios: usuarios
    licencias: licencias
  servers: localhost:29092, localhost:29093, localhost:29094

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
