server:
  port: ${CUSTOM.SERVER.PORT:8002}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

spring:
  application:
    name: licencia-service
  datasource:
    url: '{cipher}12d2d2aebbb916e21f555af5e6367d1973e4a8e23eab3462cfd33980af2df865bad4c6b8488722632d1d7ee436dd5910f226b35775532dc4f1d8f624f4b0d8c3'
    username: '{cipher}a22e6e73f963941d1ff3b5feed48da91c712e82696bd5d9c028945b66c5743b6'
    password: '{cipher}75d2949566d98f7dc1cc2dd395c60e606515f2c7f8e6905cabfcfc5c963b819c'
    driver-class-name: '{cipher}fa6fa36e44df9ba10d99b650f840f437a9b2cf9976a1ff8b1c753acd56d8902370d5dd89c6c1a16278aadd26844ae39b'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      cliente-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

kafka:
  topic: licencias
  servers: localhost:29092, localhost:29093, localhost:29094

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:licencia-service.log}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
  endpoint:
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:licencia-service.log}
