server:
  port: ${CUSTOM.SERVER.PORT:8002}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

db:
  host: ${DB.HOST:localhost}
  port: ${DB.PORT:25432}
  name: '{cipher}9be0102e332c71fe3e0ae62075312e8859bc7745dadb6dbe3e10f98746f6a351'
  type: '{cipher}5235158b1c9ddff86e5ba7778506778fe5ddc1c79dce8a05c1d69c977c79be22'

spring:
  application:
    name: licencia-service
  datasource:
    url: jdbc:${db.type}://${db.host}:${db.port}/${db.name}
    username: '{cipher}a22e6e73f963941d1ff3b5feed48da91c712e82696bd5d9c028945b66c5743b6'
    password: '{cipher}75d2949566d98f7dc1cc2dd395c60e606515f2c7f8e6905cabfcfc5c963b819c'
    driver-class-name: '{cipher}fa6fa36e44df9ba10d99b650f840f437a9b2cf9976a1ff8b1c753acd56d8902370d5dd89c6c1a16278aadd26844ae39b'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      cliente-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

kafka:
  topic: licencias
  servers: ${KAFKA.SERVERS:localhost:29092,localhost:29093,localhost:29094}

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:licencia-service.log}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.ENDPOINT:http://localhost:9411/api/v2/spans}
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:licencia-service.log}
