server:
  port: ${CUSTOM.SERVER.PORT:8889}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

spring:
  application:
    name: monitoring-service

logging:
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:monitoring-service.log}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
  endpoint:
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:monitoring-service.log}
