server:
  port: ${CUSTOM.SERVER.PORT:8001}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

db:
  host: ${DB.HOST:localhost}
  port: ${DB.PORT:15432}
  name: '{cipher}1aac4adade13a9bb9a62f9efe9cd5b8cd6293751004ce85a4333308142fa99b4'
  type: '{cipher}21708409cf3df0bb8f996f1de54f9b7f1354430002bcc91881c4c265879feaab'

spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:${db.type}://${db.host}:${db.port}/${db.name}
    username: '{cipher}a22e6e73f963941d1ff3b5feed48da91c712e82696bd5d9c028945b66c5743b6'
    password: '{cipher}d2cb3b3df2613e6a92b7621c51855773a52ce99b3dedc2e14d025cc1fd2b6dee'
    driver-class-name: '{cipher}fa6fa36e44df9ba10d99b650f840f437a9b2cf9976a1ff8b1c753acd56d8902370d5dd89c6c1a16278aadd26844ae39b'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

kafka:
  topic: usuarios
  servers: ${KAFKA.SERVERS:localhost:29092,localhost:29093,localhost:29094}

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:usuario-service.log}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.ENDPOINT:http://localhost:9411/api/v2/spans}
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:usuario-service.log}
