server:
  port: ${CUSTOM.SERVER.PORT:8001}

encrypt:
  key: ${ENCRYPT.KEY:licencium-secret-key}

spring:
  application:
    name: usuario-service
  datasource:
    url: '{cipher}8512df92b5dd3a1b01aa449cb2957cea3e786e742372891ea5b811f36f1da5868a473ec25066afdf11a67251a1d5b248d2f65fe3349194e42f2fca1bf75b43d1'
    username: '{cipher}a22e6e73f963941d1ff3b5feed48da91c712e82696bd5d9c028945b66c5743b6'
    password: '{cipher}d2cb3b3df2613e6a92b7621c51855773a52ce99b3dedc2e14d025cc1fd2b6dee'
    driver-class-name: '{cipher}fa6fa36e44df9ba10d99b650f840f437a9b2cf9976a1ff8b1c753acd56d8902370d5dd89c6c1a16278aadd26844ae39b'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

kafka:
  topic: usuarios
  servers: localhost:29092, localhost:29093, localhost:29094

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file:
    name: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:usuario-service.log}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
  endpoint:
    logfile:
      external_file: ${LOG.FILE.PATH:./logs}/${LOG.FILE.NAME:usuario-service.log}
